services:
  - type: web
    name: db-produktvergleich
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install --with-deps chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
    healthCheckPath: /api/health
    autoDeploy: true